### ISSUE TITLE
Better handling of humidity sensors

### ISSUE THREAD

**Issue by sciurius** [joba-1/Tasmoticz#27]
I have a AM2301/DHT22 sensor that reports

    "AM2301":{"Temperature":18.4,"Humidity":45.2,"DewPoint":6.3}

While this is correctly handled by Domoticz, the resultant humidity device is not considered a 'real' humidity sensor since it lacks a status indicator (normal, wet, dry etc). See e.g. https://www.domoticz.com/wiki/Dummy_for_virtual_Switches#Humidity .

Main consequence is that currently no history data is kept for such devices.

**Comment by joba-1** [comment]
how do you suggest to translate percent to the needed status? Should be easy to implement, once the definition is clear and how to tell it to domoticz

**Comment by sciurius** [comment]
TBH, I do not have the faintest idea... I'm just passing [the message](https://www.domoticz.com/forum/viewtopic.php?p=287046#p287046) through.

AFAIC always returning status `normal` would already be okay.

**Comment by joba-1** [comment]
ok, I‘ll ask there. But sending „normal“ will be doable.

**Comment by joba-1** [comment]
I have added sending „normal“ for now. Please check

**Comment by sciurius** [comment]
Confirmed. Humidity is logged now.

**Comment by sciurius** [comment]
I've noticed that even though the humidity sensor reports the humidity in tenths of percents, Domoticz seems to round the percentage to whole numbers. Is that a Domoticz issue, or a plugin issue?

**Comment by joba-1** [comment]
I wrote this comment 3 years ago, no idea if it is still true with current domoticz versions. 

[tasmota.py, line 375: # Domoticz humidity only accepted as integer](https://github.com/joba-1/Tasmoticz/blame/master/tasmota.py#L375)

to check it, feel free to change the following line to 
  return float(value), "0"
