### ISSUE TITLE
Support for Tasmota 12.1 and Tasmota Discovery / hatasmota

### ISSUE THREAD

**Issue by pizzulicchio** [joba-1/Tasmoticz#33]
Hi,
with tasmota 12.1 has been removed dedicated MQTT Home Assistant discovery in favour of Tasmota Discovery and hatasmota.
https://tasmota.github.io/docs/
https://github.com/arendst/Tasmota/releases/tag/v12.1.0

Will this change have some aftermath ? can i update my device or not ?

**Comment by joba-1** [comment]
I don’t use discovery protocols, just normal status and sensor messages. So I guess it has no influence. But I haven't tested it.

**Comment by pizzulicchio** [comment]
I'm waiting a pzem-004 sensor to use with a "tasmotized" sonoff basic. Will arrive in september.
I'll do some tests and let you know.
(I thought you were using the discovery protocol with the command: SetOption 19 )

**Comment by joba-1** [comment]
My energy monitoring devices all work just fine with domoticz and the tasmoticz plugin. I noticed no changes with recent tasmota versions. But I don’t have pzems … yet.

The design goal of tasmoticz is, to not rely on specific protocols in tasmota. setoption19, ha support, even domoticz support is not needed. But they don’t hurt either if you want to us them for something different that tasmoticz does not support (like things with sliders).

I‘d say, give it a try with one device.
If it doesn’t work I‘ll see what I can do.

**Comment by pizzulicchio** [comment]
Hi,
i have tested your plugin with tasmota build 12.1.1 with a son off TH with connected pzem-004 power monitoring too.
It's FULLY WORKING.
Only the wifi signal strenght is missing, but it wasn't present before too. (See screen in yellow)
![immagine](https://user-images.githubusercontent.com/5867711/188281649-f58ceb9d-b6fd-459d-818b-9364f4c71e98.png)

Is it possible to implement?

**Comment by joba-1** [comment]
great to hear it is working.

Regarding RSSI: Iirc I tried to implement it but it didn’t work. Maybe it’s time for another attempt. But since that’s a different story, I‘ll close this one
