### ISSUE TITLE
I am asking for two separate blocks in domoticz

### ISSUE THREAD

**Issue by Daro1003** [joba-1/Tasmoticz#44]
Friend @joba1, can you split this block in domoticz into two separate ones? Because in dashticz two blocks are shown but their name and order cannot be changed, only both blocks are under the same name because in domoticz there is one block. This block shows the total energy and the energy of yesterday. In the previous version there were two separate blocks in domoticz energy yesterday and total energy.
Please update the plugin.
![Energia całkowita11](https://github.com/joba-1/Tasmoticz/assets/53434098/67d6eef9-c2a2-4efc-bd4f-d3d86efe067c)
![Energia całkowita11](https://github.com/joba-1/Tasmoticz/assets/53434098/d998f3dc-6421-4182-b036-56dbebd2a675)

Because it is transferred to the dashboard in two separate blocks in which it is not possible to change the name or set them on the desktop. It is better if Total Energy and Yesterday Energy are two separate blocks in Domoticz
![Dashticertrerz](https://github.com/joba-1/Tasmoticz/assets/53434098/0fb9d5d5-4d58-416c-86fc-8a223eab6e8c)

**Comment by joba-1** [comment]
I also like Energy readings separated, but that is what I see. Not sure what you did to combine them. Maybe a new domoticz behaviour? Then I am the wrong guy to ask. I just wrote the plugin.

**Comment by Daro1003** [comment]
This has been the case since the beginning, when you wrote the new version of the plugin, I wrote about it on the forum. The graphs are ok nice but there are just two readings in one block device.
See, in Domoticz there is one block and in Dashticz there are two blocks whose position cannot be set or a different name cannot be set and it is not known what is going on.
Can you change something? Or where to report a problem?
Dashticz:
![Wtyczkaaa](https://github.com/joba-1/Tasmoticz/assets/53434098/9793856f-2950-4cd7-9ab5-3c7a9f675443)
Domoticz:
![DomoticzWtyczka](https://github.com/joba-1/Tasmoticz/assets/53434098/f2de68ba-9d39-494a-88c9-2dc919099b3f)

**Comment by joba-1** [comment]
Sorry, I'm not regularly visiting the forum. If you point me to the discussion, maybe I can understand better what you mean. 

I see you use dashticz which I never have heard of. No idea if I can influence what it displays and how.

I see counters of domoticz which are combined Energy Total and Energy day. Energy readings where introduced on github master branch as user hjheins pull request 8 months ago. 
Then 2 months ago I added a requested change to use counter types for energy totals. They are not yet in master but only in branch energy-totals-as-counter. I plan to merge them into master once I hear the displayed values are ok (I don't really use this myself). From the Domoticz icons it looks like you use this change already?

I don't really get what you mean with blocks. If you mean if different readings of one sensor are displayed near each other or scattered: I don't thing a plugin can have influence on that. I guess domoticz places them in the order my plugin detects and creates them.
Please ask domoticz or dashticz creators on how to place things on their guis. If my plugin can somehow do something to influence this placement, I will consider it.

**Comment by Daro1003** [comment]
The thing is that earlier in the plugin it was stated that the total energy and the energy yesterday were two devices in domoticz and two in dashticz.

And now the total energy and yesterday's energy are one device in domoticz and two in dashticz which cannot edit the name and settings.

Sorry, I'm Polish and I translate into English using Google Translator.

Can I go back to the previous version??

**Comment by Daro1003** [comment]
I read on the forum that work is underway on the next version of domoticz. Maybe you will be able to come to an agreement on the issue of energy indications and the general operation of the energy indicator.

**Comment by joba-1** [comment]
> Can I go back to the previous version??

yes. I use git and the code is on github. That means all changes (grouped by commits) can be seen in the git log: https://github.com/joba-1/Tasmoticz/commits/master/

Go down the list as far as you like and select [<>] at the right border. Push [Code] and select download zip. Replace the tasmoticz plugin folder of domoticz with the content of the zip file (or just copy over the *.py files. 

There are other ways, but that is probably easiest for you.

**Comment by joba-1** [comment]
I think I now understand better with what you mean with two blocks:

Tasmota delivers 3 energy values: Total, Today and Yesterday. Tasmoticz creates a block for each value in domoticz.
Additionally the Total block calculates and displays the Today value by itself.

I can't change the Total block behaviour. What I did is deactivating the Today device and have only the calculated value from the Total block. No need for redundant info.

**Comment by Daro1003** [comment]
So, update the plugin? Will there be changes?

**Comment by joba-1** [comment]
i have undone type change for Today and Yesterday in the PR already. No more changes planned if I don’t hear of new problems. Plan to merge this to master in a week or so.

**Comment by Daro1003** [comment]
I believe that the data offered by Tasmota regarding electricity are sufficient.

In a week, run /tasmoticz git pull? I understood ?

**Comment by Daro1003** [comment]
Hi
I ran the git checkout command and it no longer detects any of the new devices.

heelp

**Comment by joba-1** [comment]
I noticed I had a domoticz/tasmoticz device with damaged description data.
This caused updates of values and friendly names for tasmoticz devices with higher idx values to fail.

I have just updated branch energy-totals-as-counters with a fix so devices are updated again.
Also with the fix it should be easier to spot devices with damaged description data in the domoticz log to repair or delete them. Logs lines for my device 115 looked like this:

```
Jan 19 02:22:36 job4.job domoticz[6140]: Tasmoticz: tasmota::updateInfo1Devices: Set module and version for idx 115 failed: Expecting value: line 1 column 1 (char 0)
Jan 19 02:22:36 job4.job domoticz[6140]: Tasmoticz: tasmota::updateResultDevice: Update value for idx 115 failed: Expecting value: line 1 column 1 (char 0)
Jan 19 02:22:37 job4.job domoticz[6140]: Tasmoticz: tasmota::updateStatusDevices: Set friendly name for idx 115 failed: Expecting value: line 1 column 1 (char 0)
```
Maybe you want to give it a try?

Anyways, the changes to energy devices look ok to me, so merge to master will happen soon...

**Comment by Daro1003** [comment]
I can only try how to make changes??

I noticed that recently, after changes to the SP111 socket, unnecessary data from L1 L2 L3 appears, and the SP111 socket should only have data from L1.

**Comment by joba-1** [comment]
> Attention: If I change the name of a block in domoticz, this block stops being updated and stops working, and the data from tape is retrieved and a new block is added.

This sounds similar to the problem i fixed.

> I can only try how to make changes??

Updating should help. 

> I noticed that recently, after changes to the SP111 socket, unnecessary data from L1 L2 L3 appears, and the SP111 socket should only have data from L1.

As always: without logs I have to guess and cannot do much. Please provide logs to make tasmoticz better for everyone.

**Comment by Daro1003** [comment]
do you need logs from Domoticz ??

Wysłane z iPhone'a

**Comment by joba-1** [comment]
yes, please

best
* increase log level (optional)
* start logging
* restart domoticz
* restart tasmota device
* wait 1-2 teleperiods
* stop logging

It is ok to filter for lines containing tasmoticz

**Comment by Daro1003** [comment]
Hello
After updating Tasmoticz there are NO errors in the logs.
1. Lack of Energy Today - indication needed
2. Lack of energy Yesterday - indication needed
3. What does the indication marked in the picture "???" mean?
4. Display Total energy approx
For comparison:
![SP111_19 01 2023](https://github.com/joba-1/Tasmoticz/assets/53434098/814e3cf3-095a-4cd0-9d62-cd89f8df7806)
![TASSP111_19 01 2023](https://github.com/joba-1/Tasmoticz/assets/53434098/64487ea1-4687-41c0-b955-ea4aa24d1f4f)

**Comment by joba-1** [comment]
> After updating Tasmoticz there are NO errors in the logs.
> After changing the name in Tasmota everything works fine.

That sounds good :)

> * Lack of Energy Today - indication needed
> * Lack of energy Yesterday - indication needed

I don't know what "indication needed" means

> * What does the indication marked in the picture "???" mean?

In my energy devices this is the Energy Today value of the same device

**Comment by Daro1003** [comment]
1. Energy Today
2. Energy Yesterday
Can you make it like the previous version again?

     - In my energy devices this is the Energy Today value of the same device

Can it be two separate domoticz blocks?

**Comment by Daro1003** [comment]
I really liked the version before the charts were changed.
When you made a change in the charts, one domoticz block has 2 data

**Comment by Daro1003** [comment]
Wrong block type:
![Type](https://github.com/joba-1/Tasmoticz/assets/53434098/b5c081c5-0a35-49d5-bac9-e14a866c70e2)

Other than that it looks ok.

Tomorrow I will test it on the latest version of Tasmota 13

**Comment by Daro1003** [comment]
Wrong block type:
![Type](https://github.com/joba-1/Tasmoticz/assets/53434098/b5c081c5-0a35-49d5-bac9-e14a866c70e2)

For me, what needs to be changed is:

![Type](https://github.com/joba-1/Tasmoticz/assets/53434098/ec7aacb6-9fe1-4ec1-9fae-12faf3302eb6)


Other than that it looks ok.

Tomorrow I will test it on the latest version of Tasmota 13.3.0

**Comment by joba-1** [comment]
sorry, cannot help with that. Domoticz decides what is displayed there. I was surprised and a bit confused at first as well.

**Comment by Daro1003** [comment]
Then try to change this type:
![Ennn](https://github.com/joba-1/Tasmoticz/assets/53434098/434e8e02-9ace-4709-8b35-3f65e900d34f)
For a type like energy yesterday and energy today:
![nanana](https://github.com/joba-1/Tasmoticz/assets/53434098/edbd61e5-917b-42f4-889b-d8417754f070)
I would like to see what it will look like in the dashboard.
Or if possible, create an additional block total energy in the form:
![nanana](https://github.com/joba-1/Tasmoticz/assets/53434098/329a2523-85da-484d-af8b-cfd34306b7a7)

Thank you for all your work.

**Comment by joba-1** [comment]
fyi, I merged the change using the special domoticz sensor type for total energy to master now. No special branch required anymore.

See my comment in the PR #43 to see what to do if you dont't want that change.
